# Generated by Django 4.1.7 on 2023-03-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField()),
                ('property_name', models.CharField(max_length=30)),
                ('property_description', models.TextField()),
            ],
        ),
    ]
