# Generated by Django 4.1.7 on 2023-03-05 18:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyInfo', '0002_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_description',
            field=models.TextField(default=uuid.UUID('95eaf791-937b-4cf7-baed-e1ea157a6889'), editable=False),
        ),
    ]
