# Generated by Django 4.1.7 on 2023-03-05 18:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyInfo', '0003_alter_property_property_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('37b2a5fd-6876-41a2-9a31-35423144ac99'), editable=False),
        ),
    ]
