# Generated by Django 4.1.7 on 2023-03-05 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PropertyInfo', '0004_alter_property_property_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('60646431-d54c-4bd8-9896-bd95bd4e333a'), editable=False),
        ),
    ]
