# Generated by Django 4.1.7 on 2023-03-12 01:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyInfo', '0005_property_user_alter_property_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('37165ea3-273f-4119-bb50-a3cc4ae0709c'), editable=False),
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PropertyInfo.activitytype')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PropertyInfo.property')),
            ],
        ),
    ]
