# Generated by Django 4.1.7 on 2023-03-12 02:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyInfo', '0006_activitytype_alter_property_uid_activities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activities',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AddField(
            model_name='activities',
            name='location',
            field=models.CharField(default='templocation', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activities',
            name='url',
            field=models.CharField(default='tempurl', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('d984d4d1-ad8f-4587-aa8e-b204189cefea'), editable=False),
        ),
    ]
