# Generated by Django 4.1.7 on 2023-03-12 03:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyInfo', '0008_alter_property_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('bb50e035-4596-4241-bc0c-85fa65c9b232'), editable=False, unique=True),
        ),
    ]
